"""EvolutionaryScale backbones loaded through the ``esm`` SDK rather than ``transformers``.

Promoted out of the local working area, where these generators lived as standalone scripts —
which meant the code to produce ESM-C 6B and ESM3 embeddings was not in the repository at all,
and the caches they wrote could not have been regenerated by anyone else.

These need a **separate environment** built from ``requirements-esmc.txt``: the SDK caps
``transformers<4.48.2`` while the T5/Ankh tokenizer paths here are validated on 4.27-4.44, so the
two cannot share one install. There is deliberately no ``[esmc]`` extra -- see
``docs/EMBEDDING_SETUP.md`` for why one briefly existed and could not resolve.
"""

from __future__ import annotations

import glob
import os

import torch

from .base import Backend


def _require_esm():
    try:
        import esm  # noqa: F401
    except ImportError as exc:  # pragma: no cover - environment-dependent
        raise ImportError(
            "The EvolutionaryScale `esm` SDK is required for this backbone. Install it in its "
            "own environment: pip install -r requirements-esmc.txt — it caps transformers below "
            "4.48.2, which the T5/Ankh paths here are not validated against. There is no [esmc] "
            "extra, deliberately; see docs/EMBEDDING_SETUP.md."
        ) from exc


class ESMCBackend(Backend):
    """ESM-C via the SDK's public API (``esmc_600m``)."""

    def __init__(self, spec, device):
        super().__init__(spec, device)
        _require_esm()
        from esm.models.esmc import ESMC

        self.model = ESMC.from_pretrained(spec.model_id).to(device).eval()

    def _forward(self, text: str):
        from esm.sdk.api import ESMProtein, LogitsConfig

        out = self.model.logits(
            self.model.encode(ESMProtein(sequence=text)),
            LogitsConfig(return_embeddings=True),
        )
        # `[1, L+2, dim]` including BOS/EOS; the shared trimming rule removes them. Cast to
        # fp32 on CPU so a cached tensor does not depend on the device or dtype that made it —
        # runs happen on MPS bf16 and CUDA alike and must produce interchangeable caches.
        return out.embeddings.float().cpu(), None


class ESM3Backend(Backend):
    """ESM3-open.

    CPU only: ``forward()`` always runs the structure geometry track, whose fp32 autocast guard
    raises on MPS. That is a property of the multimodal model, not of this wrapper.
    """

    def __init__(self, spec, device):
        if device.type == "mps":
            device = torch.device("cpu")
        super().__init__(spec, device)
        _require_esm()
        from esm.pretrained import ESM3_sm_open_v0

        self.model = ESM3_sm_open_v0(str(device)).eval()

    def _forward(self, text: str):
        enc = self.model.tokenizers.sequence.encode(text)  # includes BOS/EOS
        toks = torch.tensor([enc], device=self.device)
        out = self.model.forward(sequence_tokens=toks)
        return out.embeddings.float().cpu(), None


class ESMC6BBackend(Backend):
    """ESM-C 6B, built by hand from the published safetensors.

    No released ``transformers`` registers the ``esmc`` architecture at this size, and the SDK's
    own registry omits the 6B — but the published shards are in native esm-package format, with
    keys prefixed ``esmc.``. Stripping that prefix loads them straight into a hand-built module.

    The module is built with **real** initialization rather than on the meta device, because
    buffers that are not in the checkpoint (rotary frequencies among them) must be valid;
    ``strict=False`` then leaves the unused LM head untouched while the shards overwrite the
    parameters that are saved.
    """

    def __init__(self, spec, device):
        if device.type == "mps":
            device = torch.device("cpu")  # registered mps_ok=False
        super().__init__(spec, device)
        _require_esm()
        from esm.models.esmc import ESMC
        from esm.tokenization import get_esmc_model_tokenizers
        from safetensors.torch import load_file

        snapshot = os.environ.get("ESMC6B_SNAPSHOT")
        if not snapshot:
            raise RuntimeError(
                "ESM-C 6B loads from a local snapshot of its safetensors shards. Set "
                "ESMC6B_SNAPSHOT to the directory containing model-*.safetensors (download it "
                f"from https://huggingface.co/{spec.model_id})."
            )
        shards = sorted(glob.glob(os.path.join(snapshot, "model-*.safetensors")))
        if not shards:
            raise FileNotFoundError(f"No model-*.safetensors under {snapshot!r}.")

        dtype = getattr(torch, os.environ.get("ESMC6B_DTYPE", "float32"))
        self.model = ESMC(
            d_model=2560, n_heads=40, n_layers=80,
            tokenizer=get_esmc_model_tokenizers(), use_flash_attn=False,
        ).eval()
        # strict=False is load-bearing (the checkpoint's unused LM head must be ignored), but it
        # also means a shard whose keys carry no `esmc.` prefix loads NOTHING and succeeds
        # silently -- leaving the hand-built module randomly initialised while still returning
        # finite, correctly-shaped tensors that pass every embed_checked assertion. Count what
        # actually landed.
        loaded = 0
        expected = len(self.model.state_dict())
        for shard in shards:
            part = load_file(shard)
            part = {k[len("esmc."):]: v for k, v in part.items() if k.startswith("esmc.")}
            own = self.model.state_dict()
            loaded += sum(1 for k in part if k in own)
            self.model.load_state_dict(part, strict=False, assign=False)
            del part
        if loaded == 0:
            raise RuntimeError(
                f"No weights loaded from {len(shards)} shard(s) under {snapshot}: no key carried "
                f"the expected 'esmc.' prefix. The model would stay randomly initialised and "
                f"still produce plausible-looking embeddings."
            )
        if loaded < 0.9 * expected:
            import warnings
            warnings.warn(
                f"Only {loaded}/{expected} parameters were matched from the checkpoint; the rest "
                f"remain at their initial values. Check that the snapshot matches the hard-coded "
                f"architecture (d_model=2560, n_heads=40, n_layers=80).", RuntimeWarning)
        self.model = self.model.to(device=device, dtype=dtype)

    def _forward(self, text: str):
        toks = self.model._tokenize([text]).to(self.device)  # [1, L+2], BOS/EOS included
        out = self.model.forward(sequence_tokens=toks)
        return out.embeddings.float().cpu(), None
